### ISSUE TITLE
Exclude creativecommons.org as a referral domain on donate.creativecommons.org

### ISSUE THREAD

**Issue by ewilfong** [creativecommons/donate.creativecommons.org#3]
Since creativecommons.org and donate.creativecommons.org are the same site from user’s point of view, we want to track the user’s movement from one domain to the other as a single session. This is set up in the Google Analytics admin settings for donate.creativecommons.org, but since that site is using the old ga.js code, it needs to be set up in the code snippet on the site.

This mix of the new analytics.js code on the main site and old code on the donate site is stretching my knowledge of how GA records data, but I think this documentation is what we’re looking for: https://developers.google.com/analytics/devguides/collection/gajs/gaTrackingSite#domainSubDomains.

Incorporating the Asynchronous syntax into the GA setup on the donate site *should* get us what we’re looking for.  Might be a bit of trial and error, to be honest.  Do we need to loop in Giant Rabbit to make changes to this section of the donate site?

This part of the example code: 
`_gaq.push(['_setDomainName', 'example-petstore.com']);`
should be
`_gaq.push(['_setDomainName', 'creativecommons.org’]);`

**Comment by mattl** [comment]
Do we want to include all CC subdomains in there? For example, wiki.creativecommons.org or the coming soon blog.creativecommons.org?

**Comment by ewilfong** [comment]
Yes, you will want to exclude for those as well. But if you use the new analytics.js code on those subdomains, excluding the referrals can be done in the GA admin interface.  We have to do it in code on donate.creativecommons.org because it is using the older ga.js code.
