### ISSUE TITLE
Civi email is stuck

### ISSUE THREAD

**Issue by little-wow** [creativecommons/donate.creativecommons.org#4]
Civi only sent the last email to half the list (53.72%), see report here: https://donate.creativecommons.org/civicrm/mailing/report?mid=574&reset=1

The process is running, but has been stuck at this percentage for 6 hours. Will monitor over the weekend, but I think there's something wrong.

**Comment by little-wow** [comment]
(I assigned @ericsteuer so he can be aware of the issue)

**Comment by mattl** [comment]
I'll take a look but our focus is on the website migration.

**Comment by mattl** [comment]
Running again now.
